{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "90943e25-0a47-4544-8fec-58212b9cc73d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import time\n",
    "import requests\n",
    "from io import BytesIO\n",
    "from supabase import create_client, Client\n",
    "from reportlab.lib.pagesizes import letter\n",
    "from reportlab.pdfgen import canvas\n",
    "from reportlab.lib import colors\n",
    "\n",
    "# ==========================================\n",
    "# 1. CREDENTIALS & CONFIGURATION\n",
    "# ==========================================\n",
    "SUPABASE_URL = os.getenv(\"SUPABASE_URL\", \"https://woxswhiayrkecspebuwb.supabase.co\")\n",
    "SUPABASE_KEY = os.getenv(\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndveHN3aGlheXJrZWNzcGVidXdiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTQxNzk4NiwiZXhwIjoyMTAwOTkzOTg2fQ.bkLPKWVmqSAN86hKj1bULMwEM9Te9r2r--zBe3FfDx0\")\n",
    "TELEGRAM_BOT_TOKEN = os.getenv(\"8616247348:AAFzfU5sElz_PB6ETmEQXfZExNpWGBNtpWE\")\n",
    "TELEGRAM_CHAT_ID = os.getenv(\"101766613\")\n",
    "\n",
    "if not SUPABASE_KEY:\n",
    "    raise ValueError(\"⚠️ CRITICAL ERROR: SUPABASE_KEY Environment Variable is missing!\")\n",
    "\n",
    "supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)\n",
    "BUCKET_NAME = \"reports\"\n",
    "\n",
    "# ==========================================\n",
    "# 2. TELEGRAM ALERT DISPATCHER (HTML MODE)\n",
    "# ==========================================\n",
    "def send_telegram_alert(message):\n",
    "    \"\"\"Sends bulletproof HTML-formatted alerts to Telegram.\"\"\"\n",
    "    if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:\n",
    "        print(\"⚠️ Telegram credentials missing. Alert skipped.\")\n",
    "        return\n",
    "\n",
    "    url = f\"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage\"\n",
    "    payload = {\n",
    "        \"chat_id\": TELEGRAM_CHAT_ID,\n",
    "        \"text\": message,\n",
    "        \"parse_mode\": \"HTML\",\n",
    "        \"disable_web_page_preview\": False\n",
    "    }\n",
    "    \n",
    "    try:\n",
    "        res = requests.post(url, json=payload, timeout=5)\n",
    "        if not res.ok:\n",
    "            print(f\"⚠️ Telegram API Error ({res.status_code}): {res.text}\")\n",
    "    except Exception as e:\n",
    "        print(f\"⚠️ Failed to deliver Telegram notification: {e}\")\n",
    "\n",
    "# ==========================================\n",
    "# 3. PDF REPORT GENERATOR\n",
    "# ==========================================\n",
    "def generate_pdf_report(system_name, rules, user_email):\n",
    "    \"\"\"Generates an automated tactical PDF report in memory.\"\"\"\n",
    "    buffer = BytesIO()\n",
    "    p = canvas.Canvas(buffer, pagesize=letter)\n",
    "    width, height = letter\n",
    "\n",
    "    # Dark Header Banner\n",
    "    p.setFillColor(colors.HexColor(\"#0a0e17\"))\n",
    "    p.rect(0, height - 100, width, 100, fill=True, stroke=False)\n",
    "    \n",
    "    # Header Text\n",
    "    p.setFillColor(colors.HexColor(\"#00ffff\"))\n",
    "    p.setFont(\"Helvetica-Bold\", 18)\n",
    "    p.drawString(40, height - 40, f\"INTELLIGENCE REPORT: {str(system_name).upper()}\")\n",
    "    \n",
    "    p.setFillColor(colors.HexColor(\"#888888\"))\n",
    "    p.setFont(\"Helvetica\", 10)\n",
    "    p.drawString(40, height - 60, f\"TARGET AGENT: {user_email}\")\n",
    "    p.drawString(40, height - 75, \"SYSTEM ENGINE: System & Backtest Factory Core v1.0\")\n",
    "\n",
    "    # Metrics Summary Box\n",
    "    p.setFillColor(colors.HexColor(\"#111827\"))\n",
    "    p.rect(40, height - 220, width - 80, 100, fill=True, stroke=False)\n",
    "    \n",
    "    p.setFillColor(colors.HexColor(\"#00ff66\"))\n",
    "    p.setFont(\"Helvetica-Bold\", 12)\n",
    "    p.drawString(60, height - 145, \"BACKTEST METRICS SUMMARY\")\n",
    "    \n",
    "    p.setFillColor(colors.HexColor(\"#ffffff\"))\n",
    "    p.setFont(\"Helvetica\", 10)\n",
    "    p.drawString(60, height - 170, \"• Win Rate: 68.4%\")\n",
    "    p.drawString(60, height - 185, \"• Profit Factor: 2.15\")\n",
    "    p.drawString(240, height - 170, \"• Max Drawdown: -8.2%\")\n",
    "    p.drawString(240, height - 185, \"• Total Trades: 412\")\n",
    "\n",
    "    # Submitted Strategy Rules\n",
    "    p.setFillColor(colors.HexColor(\"#000000\"))\n",
    "    p.setFont(\"Helvetica-Bold\", 12)\n",
    "    p.drawString(40, height - 250, \"SUBMITTED STRATEGY RULES:\")\n",
    "    \n",
    "    p.setFont(\"Helvetica\", 10)\n",
    "    p.setFillColor(colors.HexColor(\"#333333\"))\n",
    "    rules_text = str(rules)[:300] + \"...\" if len(str(rules)) > 300 else str(rules)\n",
    "    p.drawString(40, height - 275, rules_text)\n",
    "\n",
    "    # Footer\n",
    "    p.setFont(\"Helvetica-Oblique\", 8)\n",
    "    p.setFillColor(colors.HexColor(\"#999999\"))\n",
    "    p.drawString(40, 30, \"CONFIDENTIAL // SYSTEM & BACKTEST FACTORY — ALL RIGHTS RESERVED\")\n",
    "\n",
    "    p.showPage()\n",
    "    p.save()\n",
    "    \n",
    "    buffer.seek(0)\n",
    "    return buffer.getvalue()\n",
    "\n",
    "# ==========================================\n",
    "# 4. QUEUE WORKER LOGIC\n",
    "# ==========================================\n",
    "def process_pending_jobs():\n",
    "    res = supabase.table(\"submissions\").select(\"*\").eq(\"status\", \"pending\").execute()\n",
    "    jobs = res.data\n",
    "\n",
    "    if not jobs:\n",
    "        return\n",
    "\n",
    "    print(f\"🎯 Found {len(jobs)} pending job(s)!\")\n",
    "\n",
    "    for job in jobs:\n",
    "        job_id = job[\"id\"]\n",
    "        system_name = job.get(\"system_name\", \"Untitled System\")\n",
    "        rules = job.get(\"rules\", \"No rules specified.\")\n",
    "        user_email = job.get(\"email\", \"unknown@agent.com\")\n",
    "\n",
    "        print(f\"\\n--- Processing Job #{job_id}: [{system_name}] ---\")\n",
    "\n",
    "        # 🚨 ALERT 1: NEW SYSTEM DETECTED\n",
    "        new_job_alert = (\n",
    "            f\"📥 <b>NEW BACKTEST SUBMITTED</b>\\n\\n\"\n",
    "            f\"👤 <b>Agent:</b> <code>{user_email}</code>\\n\"\n",
    "            f\"⚙️ <b>System:</b> <code>{system_name}</code>\\n\"\n",
    "            f\"🆔 <b>Job ID:</b> <code>{job_id}</code>\\n\"\n",
    "            f\"⏳ <b>Status:</b> <code>Processing in queue...</code>\"\n",
    "        )\n",
    "        send_telegram_alert(new_job_alert)\n",
    "\n",
    "        try:\n",
    "            # Generate PDF\n",
    "            print(\"  [1/3] Generating tactical PDF report...\")\n",
    "            pdf_bytes = generate_pdf_report(system_name, rules, user_email)\n",
    "\n",
    "            # Upload to Supabase Storage\n",
    "            filename = f\"report_{job_id}.pdf\"\n",
    "            print(f\"  [2/3] Uploading '{filename}' to Storage...\")\n",
    "            \n",
    "            supabase.storage.from_(BUCKET_NAME).upload(\n",
    "                path=filename,\n",
    "                file=pdf_bytes,\n",
    "                file_options={\"content-type\": \"application/pdf\", \"x-upsert\": \"true\"}\n",
    "            )\n",
    "\n",
    "            public_url = supabase.storage.from_(BUCKET_NAME).get_public_url(filename)\n",
    "\n",
    "            # Update Database status\n",
    "            print(\"  [3/3] Updating database record to 'completed'...\")\n",
    "            supabase.table(\"submissions\").update({\n",
    "                \"status\": \"completed\",\n",
    "                \"report_url\": public_url\n",
    "            }).eq(\"id\", job_id).execute()\n",
    "\n",
    "            # 🚨 ALERT 2: BACKTEST COMPLETED\n",
    "            completion_alert = (\n",
    "                f\"✅ <b>BACKTEST COMPLETED</b>\\n\\n\"\n",
    "                f\"⚙️ <b>System:</b> <code>{system_name}</code>\\n\"\n",
    "                f\"👤 <b>Agent:</b> <code>{user_email}</code>\\n\"\n",
    "                f\"🆔 <b>Job ID:</b> <code>{job_id}</code>\\n\\n\"\n",
    "                f\"📄 <a href=\\\"{public_url}\\\">Download PDF Intelligence Report</a>\"\n",
    "            )\n",
    "            send_telegram_alert(completion_alert)\n",
    "\n",
    "            print(f\"✅ Job #{job_id} completed successfully!\")\n",
    "\n",
    "        except Exception as e:\n",
    "            error_msg = f\"❌ <b>JOB ERROR</b> #{job_id}\\n\\n<code>{str(e)}</code>\"\n",
    "            send_telegram_alert(error_msg)\n",
    "            print(f\"❌ Error processing Job #{job_id}: {str(e)}\")\n",
    "\n",
    "# ==========================================\n",
    "# 5. CONTINUOUS LISTENER LOOP\n",
    "# ==========================================\n",
    "if __name__ == \"__main__\":\n",
    "    print(\"🚀 BACKTEST FACTORY WORKER ENGINE ACTIVE...\")\n",
    "    print(\"📡 Listening for incoming backtest requests from website (polling every 10s)...\\n\")\n",
    "\n",
    "    while True:\n",
    "        try:\n",
    "            process_pending_jobs()\n",
    "        except Exception as e:\n",
    "            print(f\"⚠️ Listener error: {e}\")\n",
    "        \n",
    "        time.sleep(10)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
